### ISSUE TITLE
Unable to edit comments

### ISSUE THREAD

**Issue by ryandonsullivan** [Yoast/comment-hacks#7] opened 2015-06-30 00:47 UTC
When you edit comments from the WordPress dashboard, and then click the "Update Comment" button, there's a "Are you sure you want to do this?Please try again" error message.

We've replicated the issue in several environments. Deactivating the comment hacks plugin resolves the issue so it appears this may be a bug. Let me know if you need any additional details. I'm happy to provide any additional info I can. Thanks.

![editing-comments](https://cloud.githubusercontent.com/assets/1830861/8421653/24c4ee48-1e8f-11e5-9e71-436d31ebdd60.jpg)

**Comment by robneu** [comment] 2015-07-27 20:50
+1

**Comment by spearsmarketing** [comment] 2015-08-14 05:50
I'm seeing this same issue as well.

**Comment by tacoverdo** [comment] 2016-05-13 09:24
@ryandonsullivan Thanks for your report. We've been trying to replicate this issue but haven't been able to do so, so far. This means we'll need your help troubleshooting. 

Can you please follow the steps in https://yoa.st/bugreport? Please also check for [JavaScript issues](http://kb.yoast.com/article/321-how-to-find-javascript-errors-with-your-browsers-console) and what happens if you run a [conflict check](http://kb.yoast.com/article/253-how-to-check-for-plugin-conflicts).

Thanks!

**Comment by jdevalk** [comment] 2017-02-20 15:15
Closed for lack of response.

**Comment by spearsmarketing** [comment] 2017-02-20 17:49
![screen shot 2017-02-15 at 11 18 19 am](https://cloud.githubusercontent.com/assets/517213/23136493/928a23dc-f762-11e6-9001-1e594a24344e.png)

**Comment by spearsmarketing** [comment] 2017-02-20 17:49
![screen shot 2017-02-20 at 11 48 19 am](https://cloud.githubusercontent.com/assets/517213/23136499/a16af91c-f762-11e6-9afd-1fb4bf199a6e.png)

**Comment by jdevalk** [comment] 2017-02-20 18:10
Ok, testing again.

**Comment by spearsmarketing** [comment] 2017-02-20 18:10
Whenever I edit a comment and save it gives that error response.

**Comment by jdevalk** [comment] 2017-02-20 18:31
Found where it came from, weird that I couldn't reproduce it before, it has never worked.

**Comment by spearsmarketing** [comment] 2017-02-20 18:32
Good to see you found. Will an update be forthcoming then?

**Comment by jdevalk** [comment] 2017-02-20 18:34
yes, my [pull request for 1.2](https://github.com/Yoast/comment-hacks/pull/15) is open, will be reviewed by a colleague tomorrow I hope. Once it's merged I'll push out a release.

**Comment by spearsmarketing** [comment] 2017-02-20 18:34
Great to hear. Thanks!

**Closed** 2017-02-22 10:18 UTC
Labels: bug, code-review
